import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Footer from "@/components/Footer"; // Import the shared Footer component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-20">
          <Link href="/" className="text-3xl font-bold pl-10 pb+5"> {/* Increased font size & added left padding */}
            MRI simplified
          </Link>
          </header>
          <main className="min-h-screen">{children}</main>
          <Footer /> {/* Footer is now shared across all pages */}
        </body>
      </html>
  );
}
